version: 2
jobs:
  lint-and-test:
    docker:
      - image: circleci/clojure:lein-2.7.1

    steps:
      - checkout
      - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - run: sudo apt-get install nodejs
      - run: npm ci
      - run: npm test
#      - run: npm run lint

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - lint-and-test
      - deploy:
          requires:
            - lint-and-test
