version: 2
orbs:
  heroku: circleci/heroku@1.0.0
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1

    steps:
      - checkout
      - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - run: sudo apt-get install nodejs
      - run: npm ci
      - run: npm test

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build