version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1

    steps:
      - checkout
      - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - run: sudo apt-get install nodejs
      - run: npm ci
      - run: npm test
